# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField(default=0)),
                ('amt_deposited', models.IntegerField(default=0)),
                ('balance_amt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='daily_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('lorry_no', models.CharField(max_length=100)),
                ('load_type', models.CharField(max_length=100)),
                ('tonnes', models.IntegerField(default=0)),
                ('trips', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('employee_name', models.CharField(max_length=100)),
                ('amt_paid', models.IntegerField(default=0)),
                ('balance_amt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='repairs_maintanace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('mechanic_name', models.CharField(max_length=100)),
                ('amt_paid', models.IntegerField(default=0)),
                ('balance_amt', models.IntegerField(default=0)),
                ('part_name', models.IntegerField(default=0)),
                ('part_price', models.IntegerField(default=0)),
            ],
        ),
    ]
