# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_work',
            old_name='lorry_no',
            new_name='number_plate',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gold.daily_work'),
        ),
    ]
